// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sazbcttkpsoyajapqcsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhemJjdHRrcHNveWFqYXBxY3NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTM3MTksImV4cCI6MjA2ODA2OTcxOX0.rH4QM08VsoVTz25ulJ-uy5VPIJvhVpyFoz5NVL3woR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});